services:
  - type: web
    name: ragnor-real-estate
    env: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GROQ_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: ragnor-79342
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@ragnor-79342.iam.gserviceaccount.com
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: AIzaSyCXh62Gx4NC7YD_xeenwnQzNtkTWUCFv4s
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: ragnor-79342.firebaseapp.com
      - key: NEXT_PUBLIC_FIREBASE_DATABASE_URL
        value: https://ragnor-79342-default-rtdb.asia-southeast1.firebasedatabase.app
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: ragnor-79342
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: ragnor-79342.firebasestorage.app
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "830309777870"
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: 1:830309777870:web:7c15158b7326fb98b82b9f
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        value: G-KG7L2P7X7S
